version: '3.8'
services:
  my-sql:
    image: mysql:8.0
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hali_community
      MYSQL_USER: hali
      MYSQL_PASSWORD: hali
    volumes:
      - ./data:/var/lib/mysql
  flash_cards_redis:
    container_name: flash_cards_redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
  flash_cards_redis_commander:
    container_name: flash_cards_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS:local:flash_cards_redis:6379
    ports:
      - '8088:8081'
    depends_on:
      - flash_cards_redis
